DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'Username' VARCHAR(30) NOT NULL,
  'Email' VARCHAR(60) NOT NULL,
  'Password' VARCHAR(30) NOT NULL,
  'TimeAccount' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS Grps;

CREATE TABLE IF NOT EXISTS Grps(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'GroupName' VARCHAR(30) NOT NULL,
  'GroupDescription' TEXT,
  'GroupTimeCreation' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS UserJoinGroup;

CREATE TABLE IF NOT EXISTS UserJoinGroup(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'Username' VARCHAR(30) NOT NULL,
  'GroupName' VARCHAR(30) NOT NULL,
  'UserRole' VARCHAR(30) NOT NULL,
  'UserTimeJoin' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS InviteInGroup;

CREATE TABLE IF NOT EXISTS InviteInGroup(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'Username' VARCHAR(30) NOT NULL,
  'GroupName' VARCHAR(30) NOT NULL,
  'InviteMember' VARCHAR(30) NOT NULL,
  'UrlInvite' VARCHAR(60) NOT NULL,
  'UserRole' VARCHAR(30) NOT NULL,
  'Used' BOOLEAN DEFAULT FALSE,
  'UserTimeJoin' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS CVE;

CREATE TABLE IF NOT EXISTS CVE(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'CVEName' VARCHAR(30) NOT NULL,
  'CVETitle' VARCHAR(64) NOT NULL,
  'CVEDescription' TEXT NOT NULL,
  'CVEUserCreate' VARCHAR(30) NOT NULL,
  'CVEZeroDay' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  'CVELinks' TEXT,
  'CVENote' TEXT,
  'CVEConfermation' BOOLEAN DEFAULT FALSE,
  'TimeCreation' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS Tags;

CREATE TABLE IF NOT EXISTS Tags(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'TagName' VARCHAR(30) NOT NULL,
  'TagDescription' VARCHAR(30) NOT NULL,
  'TagOS' VARCHAR(30),
  'TagLanguage' VARCHAR(30),
  'TagType' VARCHAR(30),
  'TagTimeCreation' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS HasTags;

CREATE TABLE IF NOT EXISTS HasTags(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'TagName' VARCHAR(30) NOT NULL,
  'CVEName' VARCHAR(30) NOT NULL,
  'Username' VARCHAR(30) NOT NULL,
  'TagTimeUsed' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS OSTag;

CREATE TABLE IF NOT EXISTS OSTag(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'OSName' VARCHAR(30) NOT NULL,
  'OSDescription' TEXT NOT NULL,
  'TimesUsed' INT DEFAULT 0
);


DROP TABLE IF EXISTS LanguageTag;

CREATE TABLE IF NOT EXISTS LanguageTag(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'LanguageName' VARCHAR(30) NOT NULL,
  'LanguageDescription' TEXT NOT NULL,
  'TimesUsed' INT DEFAULT 0
);


DROP TABLE IF EXISTS GroupEvents;

CREATE TABLE IF NOT EXISTS GroupEvents(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'EventType' VARCHAR(30) NOT NULL,
  'EventDescription' VARCHAR(30) NOT NULL,
  'EventGroup' VARCHAR(30) NOT NULL,
  'EventUser' VARCHAR(30) NOT NULL,
  'EventTime' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS Persona;

CREATE TABLE IF NOT EXISTS Persona(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'Username' VARCHAR(30) NOT NULL,
  'Name' VARCHAR(40),
  'Surname' VARCHAR(40),
  'Mobile' VARCHAR(20),
  'Country' VARCHAR(30),
  'City' VARCHAR(60),
  'Zip' INT(6),
  'Passport' VARCHAR(40),
  'LastEdit' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS UserLite;

CREATE TABLE IF NOT EXISTS UserLite(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'Username' VARCHAR(30) NOT NULL,
  'TimeAccount' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS UserPremium;

CREATE TABLE IF NOT EXISTS UserPremium(
  'id' INT PRIMARY KEY AUTO_INCREMENT,
  'Username' VARCHAR(30) NOT NULL,
  'Card' VARCHAR(30) NOT NULL,
  'TimeAccount' TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
