version: "3"
services:
 app:
  container_name: adoring_turing1
  restart: always
  build: .
  ports:
   - "3000:3000"
  links:
   - mysql
 mysql:
  container_name: mysql
  image: mysql
  ports:
   - "3307:3307"
